; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using MEGA.
[ MEGAinfo ]
ver                              = 10200331-x86_64 Linux           
[ DataSettings ]
datatype                         = snNucleotide                    
containsCodingNuc                = True                            
MissingBaseSymbol                = ?                               
IdenticalBaseSymbol              = .                               
GapSymbol                        = -                               
Labelled Sites                   = All Sites                       
Labels to Include                =                                 
[ ProcessTypes ]
ppModelSelML                     = true                            
[ AnalysisSettings ]
Analysis                         = Model Selection (ML)            
Tree to Use                      = Automatic (Neighbor-joining tree)
User Tree File                   = Not Applicable                  
Statistical Method               = Maximum Likelihood              
Substitution Model               = ====================            
Substitutions Type               = Nucleotide                      
Data Subset to Use               = ====================            
Gaps/Missing Data Treatment      = Complete deletion               
Site Coverage Cutoff (%)         = Not Applicable                  
Select Codon Positions           = 1st, 2nd, 3rd, Non-Coding       
Branch Swap Filter               = None                            
System Resource Usage            = ====================            
Number of Threads                = 6                               
Genetic Code Table               = Not Applicable                  
Genetic Code                     = Not Applicable                  
Has Time Limit                   = False                           
Maximum Execution Time           = -1                              
